### ISSUE TITLE
Placeholder images no longer exists 

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-elements/react-native-elements-app#119]
### Description
Placeholder images referenced from `S3` are no longer available.

https://github.com/react-native-elements/react-native-elements-app/blob/next/src/views/avatars.js#L11

![Screenshot from 2020-12-15 08-09-51](https://user-images.githubusercontent.com/32242596/102161227-ec9de580-3eac-11eb-8738-359573e57b5c.png)

**Comment by HariAcidReign** [comment]
@pranshuchittora the `thumbProps` for Slider Vertical is not visible and the reason for that seems to be due to this issue. What can be done to solve this? 
![image](https://user-images.githubusercontent.com/58134096/111073336-50fc2f80-8504-11eb-8941-ebcdab85ce52.png)
![image](https://user-images.githubusercontent.com/58134096/111073386-7ab55680-8504-11eb-9ee6-e392eb311100.png)

I can pick up this issue and solve it immediately if pointed in the right direction 🙌🏻
